config/routes.rb
require 'sidekiq/web'

Magpie::Application.routes.draw do
  devise_for :admins, controllers: { sessions: "admins/sessions" }

  resources :projects do
    resources :project_layers, except: [:new] do
      match ':type' => 'project_layers#new', on: :new, as: :subclass
    end
  end

  resources :workspaces, only: [:show, :create], shallow: true do
    resources :areas_of_interest, only: [:show, :create, :update, :destroy], shallow: true do
      resources :polygons, only: [:show, :create, :update, :destroy] do
        collection do
          get "new_upload_form"
          post "create_from_file"
        end
      end
    end
  end

  resources :polygon_uploads, only: [:show]

  constraint = lambda { |request| request.env["warden"].authenticate? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  root :to => 'projects#index'
end

app/models/project_layer.rb
class ProjectLayer < ActiveRecord::Base
  attr_accessible :display_name, :is_displayed, :provider_id, :type, :statistics_attributes

  has_many :statistics, dependent: :destroy
  accepts_nested_attributes_for :statistics, reject_if: lambda { |c| c[:display_name].blank? }, allow_destroy: true

  PROJECT_LAYER_CLASSES = %w( RasterLayer ProtectedPlanetLayer BlueCarbonLayer BlueForestsLayer )

  def self.subclass(subclass_type)
    project_layer_class = PROJECT_LAYER_CLASSES[PROJECT_LAYER_CLASSES.index(subclass_type).to_i]
    project_layer_class.constantize
  end

  def self.get_operations module_name=nil
    if module_name.nil?
      class_name  = self.to_s.underscore
      module_name = "#{class_name}_operations"
    end

    operations = []

    Dir.chdir("#{Rails.root}/lib/modules/") do |dir|
      id = 0
      Dir["#{module_name}/**"].each do |file|
        next if ['base', 'templates', 'utils', module_name].include? File.basename(file, '.rb')

        operation_module = file.chomp(File.extname(file)).camelize.constantize
        operations << {
          'id'           => id,
          'name'         => operation_module::Name,
          'display_name' => operation_module::DisplayName
        }

        id += 1
      end
    end

    operations
  end

  def self.get_providers
    []
  end

  def self.fetch_result(operation, area_of_interest)
    "#{self}Operations::#{operation.to_s.classify}".constantize.perform(area_of_interest)
  end

  validates :display_name, presence: true
  validates :type, inclusion: { in: PROJECT_LAYER_CLASSES, message: "is not a valid type" }
end

app/controllers/project_layers_controller.rb
class ProjectLayersController < ApplicationController
  before_filter :authenticate_admin!
  before_filter :find_project

  respond_to :html, :json
  skip_before_filter :ensure_project

  # GET /project_layers
  # GET /project_layers.json
  def index
    @project_layers = ProjectLayer.all
    respond_with(@project_layers)
  end

  # GET /project_layers/1
  # GET /project_layers/1.json
  def show
    @project_layer = ProjectLayer.find(params[:id])
    respond_with(@project_layer)
  end

  # GET /project_layers/new
  # GET /project_layers/new.json
  def new
    @project_layer = ProjectLayer.subclass(params[:type]).new
    @providers_list = @project_layer.class.get_providers
    @operations = @project_layer.class.get_operations
    respond_with(@project_layer)
  end

  # GET /project_layers/1/edit
  def edit
    @project_layer = ProjectLayer.find(params[:id])
    @providers_list = @project_layer.class.get_providers
    @operations = @project_layer.class.get_operations
    respond_with(@project_layer)
  end

  # POST /project_layers
  # POST /project_layers.json
  def create
    @project_layer = ProjectLayer.subclass(params[:project_layer][:type]).new(params[:project_layer])
    @providers_list = @project_layer.class.get_providers
    @operations = @project_layer.class.get_operations

    rasters = @project_layer.class.get_providers
    if rasters.any?
      @project_layer.tile_url = rasters.detect { |r| r['id'] == @project_layer.provider_id }['tiles_url_format']
    end

    flash[:notice] = 'Project layer was successfully created.' if @project_layer.save
    respond_with(@project, @project_layer, location: (@project_layer.new_record? ? project_project_layers_path(@project) : project_project_layer_url(@project, @project_layer)))
  end

  # PUT /project_layers/1
  # PUT /project_layers/1.json
  def update
    @project_layer = ProjectLayer.find(params[:id])
    @providers_list = @project_layer.class.get_providers
    @operations = @project_layer.class.get_operations

    if @providers_list.length > 0
      @project_layer.tile_url = @providers_list.detect { |r| r['id'] == @project_layer.provider_id }['tiles_url_format']
    end

    flash[:notice] = 'Project layer was successfully updated.' if @project_layer.update_attributes(params[:project_layer])
    respond_with(@project, @project_layer, location: project_project_layer_url(@project, @project_layer))
  end

  # DELETE /project_layers/1
  # DELETE /project_layers/1.json
  def destroy
    @project_layer = ProjectLayer.find(params[:id])
    @project_layer.destroy
    flash[:notice] = 'Project layer was successfully destroyed.'
    respond_with(@project)
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
    @project.use
  end
end

app/helpers/project_layer_helper.rb
module ProjectLayerHelper
  def format_providers_list_for_select provider_list
    provider_list.map { |r| [r['display_name'], r['id']] }
  end

  def format_operations_list_for_select operations_list
    operations_list.map { |r| [r['display_name'], r['name']] }
  end
end

app/views/project_layers/_calculation_fields.html.erb
<tr>
  <td><%= f.input :display_name, label: false, wrapper: :default %></td>
  <td><%= f.input :unit, label: false, wrapper: :default %></td>
  <td><%= f.input :operation, collection: format_operations_list_for_select(@operations), include_blank: false, label: false, wrapper: :default %></td>
  <td>
    <%= f.input :_destroy, as: :hidden %>
    <%= link_to "#{content_tag :i, '', class: 'icon-remove'} Remove".html_safe, '#', class: "btn remove_fields" %>
  </td>
</tr>

app/views/project_layers/_form.html.erb
<%= simple_form_for(@project_layer, as: :project_layer, url: (@project_layer.new_record? ? project_project_layers_path(@project) : project_project_layer_path(@project, @project_layer)), :defaults => { :input_html => { :class => 'span8' } }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :type, as: :hidden %>
    <%= f.input :display_name %>
    <%= f.input :provider_id, collection: format_providers_list_for_select(@providers_list), include_blank: false %>
    <%= f.input :is_displayed, input_html: { class: '' } %>
  </div>

  <div class="page-header">
    <%= link_to_add_fields "Add Statistic", f, :statistics %>
    <h2>Statistics</h2>
  </div>

  <table class="statistics table table-bordered table-striped">
    <thead>
      <tr>
        <th>Display name</th>
        <th>Unit</th>
        <th>Operation</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= f.simple_fields_for :statistics, :defaults => { :input_html => { :class => '' } } do |g| %>
        <%= render 'statistic_fields', :f => g %>
      <% end %>
    </tbody>
  </table>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn-primary" %>
  </div>
<% end %>

app/views/project_layers/_statistic_fields.html.erb
<tr>
  <td><%= f.input :display_name, label: false, wrapper: :default %></td>
  <td><%= f.input :unit, label: false, wrapper: :default %></td>
  <td><%= f.input :operation, collection: format_operations_list_for_select(@operations), include_blank: false, label: false, wrapper: :default %></td>
  <td>
    <%= f.input :_destroy, as: :hidden %>
    <%= link_to "#{content_tag :i, '', class: 'icon-remove'} Remove".html_safe, '#', class: "btn remove_fields" %>
  </td>
</tr>

app/views/project_layers/edit.html.erb
<div class="page-header">
  <%= link_to :back, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <h1>Editing project layer</h1>
</div>

<%= render 'form' %>

app/views/project_layers/new.html.erb
<div class="page-header">
  <%= link_to project_path(@project), :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <h1>New <%= @project_layer.class %></h1>
</div>

<%= render 'form' %>

app/views/project_layers/show.html.erb
<div class="page-header">
  <%= link_to project_path(@project), :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to edit_project_project_layer_path(@project, @project_layer), :class => 'btn btn-primary' do %>
    <i class="icon-pencil icon-white"></i>
    Edit
  <% end %>
  <h1>Listing project layers</h1>
</div>

<dl>
  <dt>Display name:</dt>
  <dd><%= @project_layer.display_name %></dd>

  <dt>Type:</dt>
  <dd><%= @project_layer.type %></dd>

  <dt>Tile url:</dt>
  <dd><%= @project_layer.tile_url %></dd>

  <dt>Is displayed:</dt>
  <dd><%= @project_layer.is_displayed %></dd>

  <dt>Provider:</dt>
  <dd><%= @project_layer.provider_id %></dd>
</dl>

<div class="page-header">
  <h4>Statistics</h2>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Display name</th>
      <th>Unit</th>
      <th>Operation</th>
    </tr>
  </thead>

  <tbody>
<% @project_layer.statistics.each do |statistic| %>
    <tr>
      <td><%= statistic.display_name %></td>
      <td><%= statistic.unit %></td>
      <td><%= statistic.operation %></td>
    </tr>
<% end %>
  </tbody>
</table>