config/routes.rb
require 'sidekiq/web'

Magpie::Application.routes.draw do
  devise_for :admins, controllers: { sessions: "admins/sessions" }

  resources :projects do
    resources :project_layers, except: [:new] do
      match ':type' => 'project_layers#new', on: :new, as: :subclass
    end
  end

  resources :workspaces, only: [:show, :create], shallow: true do
    resources :areas_of_interest, only: [:show, :create, :update, :destroy], shallow: true do
      resources :polygons, only: [:show, :create, :update, :destroy] do
        collection do
          get "new_upload_form"
          post "create_from_file"
        end
      end
    end
  end

  resources :polygon_uploads, only: [:show]

  constraint = lambda { |request| request.env["warden"].authenticate? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  root :to => 'projects#index'
end

app/models/polygon.rb
class Polygon < ActiveRecord::Base
  attr_accessible :area_of_interest_id, :geometry

  belongs_to :area_of_interest

  before_validation do
    self.geometry = self.geometry.to_json
  end

  after_destroy do
    results = self.area_of_interest.results
    results.destroy_all
  end

  def to_geo_json
    {
      type: "Feature",
      id: id,
      properties: {},
      geometry: JSON.parse(geometry)
    }
  end

  def to_wkt
    parsed_geometry, points = JSON.parse(geometry), []

    if parsed_geometry['type'] == 'Polygon'
      parsed_geometry['coordinates'][0].each { |point| points << "#{point[0]} #{point[1]}" }

      return { id: id, the_geom: "POLYGON((#{points.join(',')}))" }
    elsif parsed_geometry['type'] == 'Circle'
      response = Net::HTTP.get_response("carbon-tool.cartodb.com", URI.escape("/api/v2/sql?format=json&q=SELECT ST_AsText(ST_Transform(ST_Buffer(ST_Transform((ST_GeomFromText('POINT(#{parsed_geometry['coordinates'][0]} #{parsed_geometry['coordinates'][1]})',4326)),900913),#{parsed_geometry['radius']}),4326))"))

      return { id: id, the_geom: JSON.parse(response.body)['rows'][0]['st_astext'] }
    end
  end
end

app/controllers/polygons_controller.rb
class PolygonsController < ApplicationController
  respond_to :json

  def show
    @polygon = Polygon.find(params[:id])
    respond_with(@polygon)
  end

  def new_upload_form
    render :layout => false
  end

  def create
    area_of_interest = AreaOfInterest.find(params[:area_of_interest_id])
    @polygon = area_of_interest.polygons.new(params[:polygon])
    flash[:notice] = 'Polygon was successfully created.' if @polygon.save
    respond_with(@polygon)
  end

  def create_from_file
    @polygon_upload = PolygonUpload.create_with_file(area_of_interest_id: params[:area_of_interest_id], file: params[:file])

    debugger
    CartodbPolygonUploadWorker.perform_async(Apartment::Database.current_database, @polygon_upload.id)

    render :layout => false
  end

  def update
    @polygon = Polygon.find(params[:id])
    flash[:notice] = 'Polygon was successfully updated.' if @polygon.update_attributes(params[:polygon])
    respond_with(@polygon)
  end

  def destroy
    @polygon = Polygon.find(params[:id])
    @polygon.destroy
    flash[:notice] = 'Polygon was successfully destroyed.'
    render json: @polygon
  end
end

app/views/polygons/create_from_file.html.erb
<html>
  <head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
      var isFinishedState = function(state) {
        return <%= PolygonUpload::FINISHED_STATES.map {|state| "state === '#{state}'" }.join("||").html_safe %>
      };

      var checkImportStatus = function () {
        console.log("checking import state:");
        $.ajax({
          type: 'GET',
          url: '<%= polygon_upload_path(@polygon_upload) %>',
          success: function(data) {
            $('#import-status').text(data.state);
            if (isFinishedState(data.state)) {
              parent.postMessage({polygonImportStatus: data.state, importMessages: data.message}, '*');
            } else {
              setTimeout(checkImportStatus, 2000);
            }
          }
        })
      };

      checkImportStatus();
    </script>
  </head>
  <body>
    Importing
    <%= image_tag 'ajax-loader.gif' %>
    <div>
      Status: <span id="import-status"></span></br>
    </div>
  </body>
</html>

app/views/polygons/new_upload_form.html.erb
<%= form_tag(create_from_file_area_of_interest_polygons_path(area_of_interest_id: params[:area_of_interest_id]), :multipart => true) do %>
  <label for="file">File to Upload</label> <%= file_field_tag "file" %><br/>
  <%= hidden_field_tag area_of_interest_id: params[:area_of_interest_id] %>
  <%= submit_tag 'Submit' %>
<% end %>