config/routes.rb
require 'sidekiq/web'

Magpie::Application.routes.draw do
  devise_for :admins, controllers: { sessions: "admins/sessions" }

  resources :projects do
    resources :project_layers, except: [:new] do
      match ':type' => 'project_layers#new', on: :new, as: :subclass
    end
  end

  resources :workspaces, only: [:show, :create], shallow: true do
    resources :areas_of_interest, only: [:show, :create, :update, :destroy], shallow: true do
      resources :polygons, only: [:show, :create, :update, :destroy] do
        collection do
          get "new_upload_form"
          post "create_from_file"
        end
      end
    end
  end

  resources :polygon_uploads, only: [:show]

  constraint = lambda { |request| request.env["warden"].authenticate? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  root :to => 'projects#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name

  validates :name, format: { with: /\A[a-z_]+\z/, message: "can only contain downcase letters and underscores (_)" }
  validate :name_cannot_start_with_pg_underscore

  after_create :prepare_project

  def use
    Apartment::Database.switch(name.downcase)
  end

  private

  def prepare_project
    Apartment::Database.create(name.downcase)
  end

  def name_cannot_start_with_pg_underscore
    if name.starts_with?('pg_')
      errors.add(:name, "can't start with 'pg_'")
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_admin!, unless: :is_it_show_json?

  respond_to :html, :json
  skip_before_filter :ensure_project

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    respond_with(@projects)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    # Switch content
    @project.use
    @layers = ProjectLayer.find(:all)

    respond_with(@project)
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    respond_with(@project)
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
    respond_with(@project)
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    flash[:notice] = 'Project was successfully created.' if @project.save
    respond_with(@project)
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])
    flash[:notice] = 'Project was successfully updated.' if @project.update_attributes(params[:project])
    respond_with(@project)
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = 'Project was successfully destroyed.'
    respond_with(@project)
  end

  private

  def is_it_show_json?
    request['action'] == 'show' && request.format.json?
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project, :defaults => { :input_html => { :class => 'span8' } }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => "btn-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <%= link_to @project, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <h1>Editing project</h1>
</div>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="page-header">
  <%= link_to new_project_path, :class => 'btn btn-primary' do %>
    <i class="icon-plus icon-white"></i>
    New Project
  <% end %>
  <h1>Listing projects</h1>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
<% @projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= link_to 'Show', project %></td>
      <td><%= link_to 'Edit', edit_project_path(project) %></td>
      <td><%= link_to 'Destroy', project, confirm: 'Are you sure?', method: :delete %></td>
    </tr>
<% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<div class="page-header">
  <%= link_to projects_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <h1>New project</h1>
</div>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="page-header">
  <%= link_to projects_path, :class => 'btn' do %>
    <i class="icon-list-alt"></i>
    Back
  <% end %>
  <%= link_to edit_project_path(@project), :class => 'btn btn-primary' do %>
    <i class="icon-pencil icon-white"></i>
    Edit
  <% end %>
  <h1>Listing projects</h1>
</div>

<dl>
  <dt>Name:</dt>
  <dd><%= @project.name %></dd>
</dl>

<div class="page-header">
  <div class="btn-group">
    <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
      <i class="icon-plus icon-white"></i>
      New Project layer
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu pull-right">
      <% ProjectLayer::PROJECT_LAYER_CLASSES.each do |subclass| %>
        <%= content_tag :li, link_to(subclass.to_s, subclass_new_project_project_layer_path(@project, type: subclass.to_s)) %>
      <% end %>
    </ul>
  </div>
  <h2>Project layers</h2>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Display name</th>
      <th>Type</th>
      <th>Tile url</th>
      <th>Is displayed</th>
      <th>Provider</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
<% ProjectLayer.all.each do |project_layer| %>
    <tr>
      <td><%= project_layer.display_name %></td>
      <td><%= project_layer.type %></td>
      <td><%= project_layer.tile_url %></td>
      <td><%= project_layer.is_displayed %></td>
      <td><%= project_layer.provider_id %></td>
      <td><%= link_to 'Show', project_project_layer_path(@project, project_layer) %></td>
      <td><%= link_to 'Edit', edit_project_project_layer_path(@project, project_layer) %></td>
      <td><%= link_to 'Destroy', project_project_layer_path(@project, project_layer), confirm: 'Are you sure?', method: :delete %></td>
    </tr>
<% end %>
  </tbody>
</table>