config/routes.rb
require 'sidekiq/web'

Magpie::Application.routes.draw do
  devise_for :admins, controllers: { sessions: "admins/sessions" }

  resources :projects do
    resources :project_layers, except: [:new] do
      match ':type' => 'project_layers#new', on: :new, as: :subclass
    end
  end

  resources :workspaces, only: [:show, :create], shallow: true do
    resources :areas_of_interest, only: [:show, :create, :update, :destroy], shallow: true do
      resources :polygons, only: [:show, :create, :update, :destroy] do
        collection do
          get "new_upload_form"
          post "create_from_file"
        end
      end
    end
  end

  resources :polygon_uploads, only: [:show]

  constraint = lambda { |request| request.env["warden"].authenticate? }
  constraints constraint do
    mount Sidekiq::Web => '/sidekiq'
  end

  root :to => 'projects#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Magpie</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <%= link_to "Magpie", root_path, :class => "brand" %>
        <div class="nav-collapse">
          <ul class="nav">
            <%= content_tag :li, link_to('Projects', projects_path), class: (params[:controller] == 'projects' ? 'active' : nil) %>
          </ul>
          <ul class="nav pull-right">
            <% if admin_signed_in? %>
              <li><%= link_to truncate("Logout #{current_admin.email}"), destroy_admin_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Login', new_admin_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert #{name == :error ? "alert-error" : "alert-success" }" do %>
        <a class="close" data-dismiss="alert" href="#">×</a>
        <%= msg %>
      <% end %>
    <% end %>
    <%= yield %>
    <hr>
    <footer>
      <p>&copy; Company 2012</p>
    </footer>
  </div>
</body>
</html>